BookSeller/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSeller.Data;
using BookSeller.Models;
using System.Security.Policy;
using Microsoft.AspNetCore.Authorization;
using BookSeller.Data.Static;

namespace BookSeller.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class AuthorsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public AuthorsController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        [AllowAnonymous]
        // GET: Authors
        public async Task<IActionResult> Index()
        {
              return View(await _context.Authors.ToListAsync());
        }
        [AllowAnonymous]
        // GET: Authors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }
            ViewBag.bookAuthor = _context.Books.Where(n => n.AuthorId == author.Id);

            return View(author);
        }

        // GET: Authors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PictureFile,FullName,Bio")] Author author)
        {
            if (!ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(author.PictureFile.FileName);
                string extension = Path.GetExtension(author.PictureFile.FileName);
                fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
                author.ProfilePictureURL = fileName;
                string path = Path.Combine(wwwRootPath + "/Img/Author", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await author.PictureFile.CopyToAsync(fileStream);
                }
                _context.Add(author);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors.FindAsync(id);
            if (author == null)
            {
                return NotFound();
            }
            return View(author);
        }

        // POST: Authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PictureFile,FullName,Bio")] Author author)
        {
            if (id != author.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(author.PictureFile.FileName);
                    string extension = Path.GetExtension(author.PictureFile.FileName);
                    fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
                    author.ProfilePictureURL = fileName;
                    string path = Path.Combine(wwwRootPath + "/Img/Author", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await author.PictureFile.CopyToAsync(fileStream);
                    }
                    _context.Update(author);
                    await _context.SaveChangesAsync();
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AuthorExists(author.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(author);
        }

        // GET: Authors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Authors == null)
            {
                return NotFound();
            }

            var author = await _context.Authors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Authors == null)
            {
                return Problem("Entity set 'AppDbContext.Authors'  is null.");
            }
            var author = await _context.Authors.FindAsync(id);
            if (author != null)
            {
                _context.Authors.Remove(author);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return _context.Authors.Any(e => e.Id == id);
        }
    }
}

BookSeller/Controllers/OrdersController.cs
using BookSeller.Data;
using BookSeller.Models;
using BookSeller.Data.Cart;
using BookSeller.Data.Service;
using BookSeller.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Printing;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using BookSeller.Data.Static;

namespace BookSeller.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;       
        public OrdersController(ShoppingCart shoppingCart, AppDbContext context, IOrderService orderService)
        {
            _shoppingCart = shoppingCart;
            _context = context;
            _orderService = orderService;          
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderService.GetOrderByUserIdAndRoleAsync(userId,userRole);
            return View(order);
        }
        public async Task<IActionResult> OrderComfirmed()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderService.GetComfirmedOrderByUserIdAndRoleAsync(userId, userRole);
            return View(order);
        }
        public async Task<IActionResult> OrderDelete()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var order = await _orderService.GetDeleteOrderByUserIdAndRoleAsync(userId, userRole);
            return View(order);
        }
        public IActionResult ShoppingCart()
        {
            var item = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = item;
            var response = new ShoppingCartViewModel()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal(),
            };
            return View(response);
        }
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if(item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _context.Books
                .Include(b => b.Author)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder(string name, string address, string phone)
        {
            if(string.IsNullOrEmpty(name) || string.IsNullOrEmpty(address)|| string.IsNullOrEmpty(phone)){
               return RedirectToAction(nameof(Checkout));
            }
            var item = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string Name = name;
            string PhoneNumber = phone;
            string Address = address;
            await _orderService.StoreOrderAsync(item, userId, Name, PhoneNumber, Address);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");           
        }
        public async Task<IActionResult> Checkout()
        {
            ViewBag.shoppingCart = _shoppingCart.GetShoppingCartItems();            
            ViewBag.Total = _shoppingCart.GetShoppingCartTotal();
            return View();
        }
        public async Task<IActionResult> Details(int id)
        {
            var order = await _orderService.GetOrderByIdAsync(id);
            if(order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        public async Task<IActionResult> ChangeStt(int OrderId,int stt)
        {
            await _orderService.ChageOrderStatus(OrderId, stt);           
            return RedirectToAction(nameof(Index));
        }
    }
}

BookSeller/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookSeller.Data;
using BookSeller.Models;

namespace BookSeller.Controllers
{
    public class PublishersController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PublishersController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Publishers
        public async Task<IActionResult> Index()
        {
              return View(await _context.Publishers.ToListAsync());
        }

        // GET: Publishers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Publishers == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }
            ViewBag.bookPublisher = _context.Books.Where(n => n.AuthorId == publisher.Id);
            return View(publisher);
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,PictureFile,Bio")] Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                string wwwRootPath = _webHostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(publisher.PictureFile.FileName);
                string extension = Path.GetExtension(publisher.PictureFile.FileName);
                fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
                publisher.ProfilePictureURL = fileName;
                string path = Path.Combine(wwwRootPath + "/Img/Publisher", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await publisher.PictureFile.CopyToAsync(fileStream);
                }
                _context.Add(publisher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Publishers == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers.FindAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,PictureFile,Bio")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string fileName = Path.GetFileNameWithoutExtension(publisher.PictureFile.FileName);
                    string extension = Path.GetExtension(publisher.PictureFile.FileName);
                    fileName += DateTime.Now.ToString("ddMMyyyy") + extension;
                    publisher.ProfilePictureURL = fileName;
                    string path = Path.Combine(wwwRootPath + "/Img/Publisher", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await publisher.PictureFile.CopyToAsync(fileStream);
                    }
                    _context.Update(publisher);
                    await _context.SaveChangesAsync();                 
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublisherExists(publisher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Publishers == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Publishers == null)
            {
                return Problem("Entity set 'AppDbContext.Publishers'  is null.");
            }
            var publisher = await _context.Publishers.FindAsync(id);
            if (publisher != null)
            {
                _context.Publishers.Remove(publisher);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublisherExists(int id)
        {
          return _context.Publishers.Any(e => e.Id == id);
        }
    }
}

BookSeller/Views/Books/Create.cshtml
@using BookSeller.Data.ViewModels
@model BookViewModel
@{
	ViewData["Title"] = "Thêm sách mới";
}

<div class="row">
	<div class="col-md-8 offset-2">
		<p>
			<h4>Thêm sách mới</h4>
		</p>

		<div class="row">
			<div class="col-md-8 offset-2">
				<form asp-action="Create" enctype="multipart/form-data">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label asp-for="Name" class="control-label"></label>
								<input asp-for="Name" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="PublisherId" class="control-label"></label>
								<select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
								<span asp-validation-for="PublisherId" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="Price" class="control-label"></label>
								<input asp-for="Price" type="number" class="form-control" />
								<span asp-validation-for="Price" class="text-danger"></span>
							</div>
							<div class="col-form-label">
								<label asp-for="PictureFile" class="control-label"></label>
								<input asp-for="PictureFile" accept="image/*" />
								<span asp-validation-for="PictureFile" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label asp-for="AuthorId" class="control-label"></label>
								<select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
								<span asp-validation-for="AuthorId" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="PublishingYear" class="control-label"></label>
								<input asp-for="PublishingYear" type="number" class="form-control" />
								<span asp-validation-for="PublishingYear" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="CategoryId" class="control-label"></label>
								<select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
								<span asp-validation-for="CategoryId" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<label asp-for="Description" class="control-label"></label>
								<textarea asp-for="Description" class="form-control"></textarea>
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
					</div>

					<div class="col-md-4 offset-4 text-center">
						<img width="100%" id="ImageUrlPreview" />
					</div>

					<div class="form-group">
						<input type="submit" value="Create" class="btn btn-outline-success float-end" />
						<a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
					</div>

				</form>

			</div>
		</div>

	</div>
</div>


@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

BookSeller/Views/Books/Delete.cshtml
@model BookSeller.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageURL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookSeller/Views/Books/Details.cshtml
@model BookSeller.Models.Book

@{
    ViewData["Title"] = "Details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                    <a asp-action="Edit" asp-route-id="@Model.Id" class="text-white float-end"><i class="bi bi-pencil-square"></i></a>
                                }
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@("/Img/Book/"+Model.ImageURL)" style="width:100%"  alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Nhà xuất bản: </b>
                            <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.Publisher.Id" style="text-decoration-line: none;">
                                @Model.Publisher.FullName
                            </a>
                        </p>                      
                        <p class="card-text">
                            <b>Thể Loại: @Model.Category.Name </b>@{
                            
                        }</p>
                        <p class="card-text"><b> Năm Xuất Bản: </b>@Model.PublishingYear</p>                                            
                        <p class="card-text">
                            <b>Tác giả: </b>
                            <hr />
                            <div class="row">                             
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@("/Img/Author/"+Model.Author.ProfilePictureURL)" style="max-width: 150px" />
                                        <br />
                                    <a asp-controller="Authors" asp-action="Details" asp-route-id="@Model.Author.Id" style="text-decoration-line: none;">@Model.Author.FullName</a>
                                    </div>                             
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12 mb-2">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-start" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white float-end"
                               asp-controller="Orders"
                               asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Thêm vào giỏ hàng (@Model.Price.ToString("#,###") VNĐ)</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BookSeller/Views/Books/Edit.cshtml
@using BookSeller.Data.ViewModels
@model BookEditViewModel

@{
	ViewData["Title"] = "Chỉnh sửa sách";	
}

<div class="row">
	<div class="col-md-8 offset-2">
		<p>
			<h4>Chỉnh sửa sách</h4>
		</p>

		<div class="row">
			<div class="col-md-8 offset-2">
				<form asp-action="Edit" enctype="multipart/form-data">
					<div asp-validation-summary="ModelOnly" class="text-danger"></div>

					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<label asp-for="Name" class="control-label"></label>
								<input asp-for="Name" class="form-control" />
								<span asp-validation-for="Name" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="PublisherId" class="control-label"></label>
								<select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
								<span asp-validation-for="PublisherId" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="Price" class="control-label"></label>
								<input asp-for="Price" type="number" class="form-control" />
								<span asp-validation-for="Price" class="text-danger"></span>
							</div>
							<div class="col-form-label">
								<label asp-for="PictureFile" class="control-label"></label>
								<input asp-for="PictureFile" accept="image/*" />
								<span asp-validation-for="PictureFile" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<label asp-for="AuthorId" class="control-label"></label>
								<select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
								<span asp-validation-for="AuthorId" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="PublishingYear" class="control-label"></label>
								<input asp-for="PublishingYear" type="number" class="form-control" />
								<span asp-validation-for="PublishingYear" class="text-danger"></span>
							</div>
							<div class="form-group">
								<label asp-for="CategoryId" class="control-label"></label>
								<select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
								<span asp-validation-for="CategoryId" class="text-danger"></span>
							</div>
						</div>
						<div class="col-md-12">
							<div class="form-group">
								<label asp-for="Description" class="control-label"></label>
								<textarea asp-for="Description" class="form-control"></textarea>
								<span asp-validation-for="Description" class="text-danger"></span>
							</div>
						</div>
					</div>
					<div class="form-group">
						<input type="submit" value="Save" class="btn btn-outline-success float-end" />
						<a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
					</div>

				</form>

			</div>
		</div>

	</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookSeller/Views/Books/Index.cshtml
@model IEnumerable<BookSeller.Models.Book>

@{
	ViewData["Title"] = "Index";
}

<h1>Chào mừng</h1>

<div class="row ">
	@foreach (var item in Model)
	{
		<div class="col-md-4 col-xs-6 border-primary mb-3">
			<div class="card mb-3" style="max-width: 540px;">
				<div class="row g-0">
					<div class="col-md-12">
						<div class="card-header text-white bg-info">
							<p class="card-text">
								<h5 class="card-title">
									@item.Name
									@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
									{
										<a asp-action="Edit" asp-route-id="@item.Id" class="text-white float-end"><i class="bi bi-pencil-square"></i></a>
									}
								</h5>
							</p>
						</div>
					</div>
					<div class="col-md-6 ">
						<a asp-action="Details" asp-route-id="@item.Id">
						<img class="border border-dark rounded" src="@("/Img/Book/"+item.ImageURL)" style="min-height: 325px;" width="100%" alt="@item.Name">
						</a>
					</div>
					<div class="col-md-6">
						<div class="card-body">
							@*<p class="card-text">@item.Description</p>*@
							<p class="card-text"><b>Tác giả: </b>@item.Author.FullName</p>
							<p class="card-text"><b>Thể Loại: </b>@item.Category.Name</p>
							<p class="card-text"><b>Năm Xuất Bản: </b>@item.PublishingYear</p>
							<p class="card-text"><b>Giá:  </b>@item.Price.ToString("#,###") VNĐ</p>

						</div>
					</div>
					<div class="col-md-12">
						<div class="card-footer ">
							<p class="card-text">
								<a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary" style="float:right"><i class="bi bi-eye-fill"></i> Xem chi tiết</a>
								<a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id"><i class="bi bi-cart-plus"></i> Thêm vào giỏ hàng </a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	}
</div>

@await Html.PartialAsync("_CreateItem", "Books")

@section Scripts{
	<script>
		var activities = document.getElementById("categoryBooks");
		activities.addEventListener("change", function () {
			if (activities.value == "0") {
				goIndex();
			}
			else{
				goCategory();
			}
		});
		function goIndex(){
			var url = '@Url.Action("Index", "Books")';
			window.location.href = url;
		}
		function goCategory(){
			var url = '@Url.Action("Category", "Books")?category=' + activities.value;
			window.location.href = url;
		}
	</script>
}